"""Add response_text to UserRequest

Revision ID: 98b2b153d25e
Revises: 
Create Date: 2024-07-08 22:47:31.734488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b2b153d25e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_profile')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=False))
        batch_op.alter_column('interests',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.drop_column('age')
        batch_op.drop_column('education_level')

    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_column('response_text')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_level', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.alter_column('interests',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('gender')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('email')

    op.create_table('_alembic_tmp_user_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('birthdate', sa.DATE(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('interests', sa.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
